// The Office's material library (Final Design Spec §01): honed travertine,
// white oak, oak slats on black felt, walnut, microcement, low-iron glass,
// brushed bronze, blackened steel, linen, leather and wool. No chrome, no
// gold. PBR throughout; maps are Basis-compressed KTX2 streamed from the
// asset route, with an on-device fallback generated by texgen.js.
//
// Geometry carries UVs in metres, so one texture tile always covers its real
// size (texgen MATERIAL_SPEC.metres) whatever the object.
import * as THREE from '../vendor/three.js?v=__UI_VERSION__';
import { ASSETS } from './asset-manifest.js?v=__UI_VERSION__';
import { MATERIAL_SPEC, generateMaterial } from './texgen.js?v=__UI_VERSION__';

export const assetUrl = (name) => (ASSETS[name] ? `./ui/office-assets/${name}?v=${ASSETS[name].v}` : null);

// Base parameters. finish → which texture set; colour multiplies the map.
const DEFINITIONS = {
  travertine: { finish: 'travertine', color: '#ffffff', roughness: 0.55, normalScale: 0.5 },
  oak: { finish: 'oak', color: '#ffffff', roughness: 0.62, normalScale: 0.7 },
  slat: { finish: 'slat', color: '#ffffff', roughness: 0.75, normalScale: 0.6 },
  // Furniture tops: white oak with grain only (no floor-plank seams), oiled.
  oakTop: { finish: 'slat', color: '#f1e4d0', roughness: 0.55, normalScale: 0.4 },
  felt: { finish: 'felt', color: '#ffffff', roughness: 1, normalScale: 0.5 },
  walnut: { finish: 'walnut', color: '#ffffff', roughness: 0.42, normalScale: 0.4, physical: { clearcoat: 0.35, clearcoatRoughness: 0.35 } },
  microcement: { finish: 'microcement', color: '#ffffff', roughness: 0.82, normalScale: 0.5 },
  plaster: { finish: 'microcement', color: '#f4f1ec', roughness: 0.9, normalScale: 0.3 },
  linen: { finish: 'linen', color: '#ffffff', roughness: 0.95, normalScale: 0.6 },
  linenDark: { finish: 'linen', color: '#8f877a', roughness: 0.95, normalScale: 0.6 },
  bronze: { finish: 'bronze', color: '#7b5d3c', roughness: 0.42, metalness: 1, normalScale: 0.3 },
  brass: { finish: 'bronze', color: '#b38f5a', roughness: 0.32, metalness: 1, normalScale: 0.2 },
  steel: { finish: 'bronze', color: '#2a2826', roughness: 0.5, metalness: 0.8, normalScale: 0.2 },
  leather: { finish: 'leather', color: '#ffffff', roughness: 0.6, normalScale: 0.6 },
  leatherTan: { finish: 'leather', color: '#c48a5c', roughness: 0.58, normalScale: 0.6 },
  wool: { finish: 'wool', color: '#ffffff', roughness: 1, normalScale: 0.8 },
  woolSand: { finish: 'wool', color: '#d8cbb6', roughness: 1, normalScale: 0.8 },
  woolSlate: { finish: 'wool', color: '#6f7378', roughness: 1, normalScale: 0.8 },
  ceramic: { color: '#ece6dc', roughness: 0.35 },
  ceramicDark: { color: '#3d3a36', roughness: 0.4 },
  paper: { color: '#f3efe6', roughness: 0.9 },
  rubber: { color: '#1c1c1c', roughness: 0.8 },
  screenBezel: { color: '#141414', roughness: 0.35, metalness: 0.2 },
  monitorBack: { color: '#cfcac2', roughness: 0.45, metalness: 0.1 },
  soil: { color: '#3b3128', roughness: 1 },
  bark: { color: '#6d6152', roughness: 0.95 },
  terrace: { finish: 'travertine', color: '#c9c3b8', roughness: 0.8, normalScale: 0.4 },
  lawn: { finish: 'microcement', color: '#b7b19f', roughness: 1, normalScale: 0.2 },
  water: { color: '#4f6a72', roughness: 0.08, metalness: 0.1 },
  glass: { color: '#e9f0f0', roughness: 0.04, metalness: 0, transparent: true, opacity: 0.1, depthWrite: false, envMapIntensity: 1.6 },
  frosted: { color: '#f2f2ef', roughness: 0.55, transparent: true, opacity: 0.62, depthWrite: false },
  whiteboard: { color: '#f7f7f5', roughness: 0.18 },
  cork: { color: '#b89670', roughness: 0.95 },
};
// Book spines and other small colour accents (one material, per-instance colours).
export const BOOK_COLORS = Object.freeze(['#e9e2d3', '#c9bfae', '#8a7f70', '#5d564c', '#2f2c28', '#d8cdb8', '#b5a891', '#efe9dc']);

export function createMaterials({ renderer, tier = 'balanced', onProgress = () => {} } = {}) {
  const made = new Map();
  const textures = [];
  const finishes = new Map(); // finish → { map, roughnessMap, normalMap, aoMap }
  const anisotropy = Math.min(tier === 'high' ? 8 : tier === 'balanced' ? 4 : 2, renderer.capabilities.getMaxAnisotropy?.() || 1);

  const get = (name) => {
    if (made.has(name)) return made.get(name);
    const definition = DEFINITIONS[name];
    if (!definition) throw new Error(`unknown material ${name}`);
    const { finish, physical, normalScale = 1, ...params } = definition;
    const material = physical ? new THREE.MeshPhysicalMaterial({ ...params, ...physical }) : new THREE.MeshStandardMaterial(params);
    material.userData.finish = finish || null;
    material.userData.normalScale = normalScale;
    material.name = name;
    made.set(name, material);
    if (finish && finishes.has(finish)) applyFinish(material, finishes.get(finish));
    return material;
  };
  const applyFinish = (material, set) => {
    material.map = set.map; material.roughnessMap = set.orm; material.metalnessMap = material.metalness > 0 ? set.orm : null;
    material.normalMap = set.normal; material.normalScale.set(material.userData.normalScale, material.userData.normalScale);
    material.needsUpdate = true;
  };
  const prepare = (texture, metres, srgb) => {
    texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
    texture.repeat.set(1 / metres, 1 / metres);
    texture.anisotropy = anisotropy;
    texture.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    textures.push(texture);
    return texture;
  };
  const install = (finish, set) => {
    finishes.set(finish, set);
    for (const material of made.values()) if (material.userData.finish === finish) applyFinish(material, set);
  };

  // On-device fallback: the same finishes, generated small.
  const generate = (finish) => {
    const size = tier === 'light' ? 128 : 256;
    const maps = generateMaterial(finish, { size, normalSize: size });
    const texture = (data, srgb) => { const made = new THREE.DataTexture(data, size, size, THREE.RGBAFormat); made.generateMipmaps = true; made.minFilter = THREE.LinearMipmapLinearFilter; made.magFilter = THREE.LinearFilter; made.needsUpdate = true; return prepare(made, maps.metres, srgb); };
    install(finish, { map: texture(maps.albedo, true), orm: texture(maps.orm, false), normal: texture(maps.normal, false) });
  };

  // Streams the KTX2 sets; any failure falls back to generated maps.
  const load = async ({ timeoutMs = 12_000 } = {}) => {
    const wanted = [...new Set(Object.values(DEFINITIONS).map((definition) => definition.finish).filter(Boolean))];
    // Hero finishes first: they cover the floor.
    wanted.sort((a, b) => ['travertine', 'oak'].indexOf(b) - ['travertine', 'oak'].indexOf(a));
    let loader = null;
    try {
      loader = new THREE.KTX2Loader().setTranscoderPath('./ui/office-assets/basis/').setWorkerLimit(2).detectSupport(renderer);
    } catch { loader = null; }
    const one = (name, srgb, metres) => new Promise((resolve, reject) => {
      const url = assetUrl(name);
      if (!loader || !url) return reject(new Error(`no ${name}`));
      const timer = setTimeout(() => reject(new Error('timeout')), timeoutMs);
      loader.load(url, (texture) => { clearTimeout(timer); resolve(prepare(texture, metres, srgb)); }, undefined, (error) => { clearTimeout(timer); reject(error); });
    });
    let done = 0; let compressed = 0;
    await Promise.all(wanted.map(async (finish) => {
      const metres = MATERIAL_SPEC[finish].metres;
      try {
        const [map, orm, normal] = await Promise.all([one(`materials/${finish}-albedo.ktx2`, true, metres), one(`materials/${finish}-orm.ktx2`, false, metres), one(`materials/${finish}-normal.ktx2`, false, metres)]);
        install(finish, { map, orm, normal }); compressed += 1;
      } catch { generate(finish); }
      done += 1; onProgress(done / wanted.length);
    }));
    loader?.dispose();
    return { compressed, generated: wanted.length - compressed };
  };

  // Night: the travertine's roughness shifts (0.55 → 0.4); nothing else changes.
  const setTravertineRoughness = (value) => { if (made.has('travertine')) made.get('travertine').roughness = value; };

  return {
    get, load, setTravertineRoughness, definitions: DEFINITIONS,
    dispose() { for (const material of made.values()) material.dispose(); for (const texture of textures) texture.dispose(); },
  };
}

// Box-projected UVs in metres from world positions and normals, for merged
// static geometry: floors use (x, z), walls (x or z, y).
export function metreUVs(geometry) {
  const position = geometry.attributes.position;
  const normal = geometry.attributes.normal;
  const uv = new Float32Array(position.count * 2);
  for (let index = 0; index < position.count; index += 1) {
    const [x, y, z] = [position.getX(index), position.getY(index), position.getZ(index)];
    const [nx, ny, nz] = [Math.abs(normal.getX(index)), Math.abs(normal.getY(index)), Math.abs(normal.getZ(index))];
    if (ny >= nx && ny >= nz) { uv[index * 2] = x; uv[index * 2 + 1] = z; }
    else if (nx >= nz) { uv[index * 2] = z; uv[index * 2 + 1] = y; }
    else { uv[index * 2] = x; uv[index * 2 + 1] = y; }
  }
  geometry.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
  return geometry;
}
